### ISSUE TITLE
Message Bridge stops working after a while

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/backend#3]
I had to restart the task to launch a new message bridge, because not message were forwarded from nRF Cloud.

We need better health monitoring of the bridge that checks, that message are coming through. This should be solved using a lambda that publishes a device message to nRF Cloud every minute and waits for the message to arrive the websocket within 10 seconds, if it arrives, health is good, if not health is bad. Record outcome in Cloudwatch Metrics, so we can set up alerts.

- device ID: `health-check`
- fingerprint: `29a.ch3ckr`

Additional metrics to add:
- [x] #49

**Comment by pudkrong** [comment]
We have added metrics
- `checkMessageFromWebsocket` is number of health check run
- `success` is number of success
- `fail` is number is fail
- `receivingMessageDuration` is duration in seconds from sending message from simulator device until it arrives through the websocket

**Comment by pudkrong** [comment]
@coderbyheart For the metric `time between message creation and when it arrives at Message bridge`, just want to confirm you want to track a time between message creation to **Message bridge**.

Is it ok to capture this metric via IoT rule?

**Comment by coderbyheart** [comment]
> @coderbyheart For the metric `time between message creation and when it arrives at Message bridge`, just want to confirm you want to track a time between message creation to **Message bridge**.

`time between message creation and when it arrives at Message bridge` = time of message retrieved by message bridge - time of creation

where

- time of message retrieved by message bridge = when the message bridge receives the message on the Account Device connection
- time of creation = the timestamp in the lambda that starts the health check

> Is it ok to capture this metric via IoT rule?

As long as that does not change the time, yes.
